version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12  
    commands:
      - echo "Installing Python dependencies"
      - sudo apt update
      - sudo apt install -y python3.12-venv
      - python3 -m venv venv
      - source venv/bin/activate
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements file"; fi
  pre_build:
    commands:
      - echo "Checking Python version"
      - python --version
  build:
    commands:
      - echo "Starting Flask app"
      - nohup python app.py &  # Run Flask app in the background
  post_build:
    commands:
      - echo "Validating Flask app"
      - curl http://localhost:5000/ || echo "Flask app did not start"
      - echo "Build completed successfully"
      - ls -al  # List files for verification

artifacts:
  files:
    - 'app.py'
    - 'requirements.txt'
    - 'static/**/*'
    - 'templates/**/*'

cache:
  paths:
    - '/root/.cache/pip/**/*'
