version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12  # Use Python 3.12 as you installed it with apt
    commands:
      - echo "Installing Python dependencies"
      - sudo apt update
      - sudo apt install -y python3.12-venv
      - python3 -m venv venv   # Create the virtual environment
      - source venv/bin/activate  # Activate the virtual environment
      - pip install -r requirements.txt  # Install required dependencies from the requirements.txt
  pre_build:
    commands:
      - echo "Checking Python version"
      - python --version  # Check Python version
  build:
    commands:
      - echo "Starting Flask app"
      - python app.py &  # Run the Flask app in the background (replace with your start command)
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'  # Include all files in the artifact
    - '!**/tests/**/*'  # Exclude test files if not needed for deployment
    - 'dist/*'  # Include the dist directory for artifacts created in the build
    - 'app.py'  # Include your app script specifically
    - 'requirements.txt'  # Include the requirements for deployment

cache:
  paths:
    - '/root/.cache/pip/**/*'  # Cache pip dependencies to speed up builds
